<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SupportToolsServer\SupportToolsServer.Application\SupportToolsServer.Application.csproj" />
    <ProjectReference Include="..\..\SupportToolsServer\SupportToolsServer.Domain\SupportToolsServer.Domain.csproj" />
    <ProjectReference Include="..\..\SystemTools\SystemTools.DatabaseToolsShared\SystemTools.DatabaseToolsShared.csproj" />
  </ItemGroup>

</Project>
